### ISSUE TITLE
TJBot Deamon bootstrapping errors

### ISSUE THREAD

**Issue by TheVinhLuong102** [jweisz/tjbot-daemon#3]
Hi Justin,

I encounter the following error when trying to activate the TJBot Daemon:

```
sudo node tjbot-daemon.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'bleno'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/Desktop/tjbot-daemon/tjbot-daemon.js:18:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Could you let me know what this error means?

Thank you very much!

**Comment by TheVinhLuong102** [comment]
Hi @jweisz I'm retrying the TJBot Daemon boostrapping and getting lots of errors. I have attached the log in a file here for your review. Thank you very much.
[TJBot-Daemon-Installation.log](https://github.com/jweisz/tjbot-daemon/files/5541927/TJBot-Daemon-Installation.log)
